name: iOS Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    # 1. リポジトリをチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. ディレクトリ移動（以降のステップはこのディレクトリ内で実行）
    - name: Set working directory
      run: cd forexgame/MyiOSApp
      shell: bash

    # 3. CocoaPods があればインストール
    - name: Install dependencies
      run: |
        if [ -f "Podfile" ]; then
          pod install
        fi
      working-directory: forexgame/MyiOSApp

    # 4. Xcodeでアーカイブ作成
    - name: Build app (archive)
      run: |
        xcodebuild \
          -project MyiOSApp.xcodeproj \
          -scheme MyiOSApp \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $PWD/build/MyiOSApp.xcarchive archive
      working-directory: forexgame/MyiOSApp

    # 5. .ipaにエクスポート
    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath $PWD/build/MyiOSApp.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath $PWD/build
      working-directory: forexgame/MyiOSApp

    # 6. .ipaをArtifactとしてアップロード
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyiOSApp-ipa
        path: forexgame/MyiOSApp/build/*.ipa
