name: iOS Build

permissions:
  contents: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    # 1. リポジトリをチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    # 2. CocoaPods があればインストール
    - name: Install dependencies
      run: |
        if [ -f "MyiOSApp/Podfile" ]; then
          pod install --project-directory=MyiOSApp
        fi

    # 3. Provisioning Profile を復元
    - name: Decode and install provisioning profile
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "$MOBILEPROVISION" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/MyiOSApp.mobileprovision
      env:
        MOBILEPROVISION: ${{ secrets.MOBILEPROVISION }}

    # 4. 証明書を Keychain にインポート
    - name: Import certificate to keychain
      run: |
        echo "$CERTIFICATE" | base64 --decode > /tmp/certificate.p12
        security create-keychain -p "$CERTIFICATE_PASSWORD" build.keychain
        security import /tmp/certificate.p12 -k ~/Library/Keychains/build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
        security list-keychains -s ~/Library/Keychains/build.keychain
        security default-keychain -s ~/Library/Keychains/build.keychain
        security unlock-keychain -p "$CERTIFICATE_PASSWORD" ~/Library/Keychains/build.keychain
        security set-key-partition-list -S apple-tool:,apple: -s -k "$CERTIFICATE_PASSWORD" ~/Library/Keychains/build.keychain
        security find-identity -v -p codesigning || true
      env:
        CERTIFICATE: ${{ secrets.CERTIFICATE }}
        CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}

    # 5. Xcode クリーン & アーカイブ（CURRENT_PROJECT_VERSION で自動インクリメント）
    - name: Clean and build archive
      working-directory: MyiOSApp
      run: |
        set -e
        rm -rf ~/Library/Developer/Xcode/DerivedData
        # Xcode でのクリーン
        xcodebuild clean -project MyiOSApp.xcodeproj -scheme MyiOSApp -configuration Release
        # アーカイブ作成
        xcodebuild \
          -project MyiOSApp.xcodeproj \
          -scheme MyiOSApp \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $PWD/build/MyiOSApp.xcarchive \
          archive \
          CODE_SIGN_STYLE=Automatic \
          DEVELOPMENT_TEAM="${{ secrets.TEAM_ID }}" \
          CURRENT_PROJECT_VERSION=$GITHUB_RUN_NUMBER

    # 6. .ipa にエクスポート
    - name: Export IPA
      working-directory: MyiOSApp
      run: |
        set -e
        xcodebuild -exportArchive \
          -archivePath $PWD/build/MyiOSApp.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath $PWD/build
        ls -al build || true

    # 7. Artifact としてアップロード
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyiOSApp-ipa
        path: MyiOSApp/build/*.ipa

    # 8. Render 配布用 static/ にコピー
    - name: Prepare static directory
      run: |
        mkdir -p MyiOSApp/static
        cp MyiOSApp/build/*.ipa MyiOSApp/static/ || echo "No ipa to copy"
        cp -f MyiOSApp/Manifest.plist MyiOSApp/static/ 2>/dev/null || true
        cp -f MyiOSApp/index.html MyiOSApp/static/ 2>/dev/null || true

    # 9. static/ をコミット & Push
    - name: Commit and push static files
      env:
        GIT_AUTHOR_NAME: github-actions
        GIT_AUTHOR_EMAIL: github-actions@github.com
      run: |
        set -e
        git config user.name "${GIT_AUTHOR_NAME}"
        git config user.email "${GIT_AUTHOR_EMAIL}"
        git add MyiOSApp/static || true
        git commit -m "Deploy ipa to static for Render (build $GITHUB_RUN_NUMBER) [skip ci]" || echo "No changes to commit"
        git push origin main || echo "Push failed (maybe permissions)"
