# 修正前
- name: Upload IPA
  uses: actions/upload-artifact@v3
  with:
    name: ios-app
    path: build/*.ipa

# 修正後
- name: Upload IPA
  uses: actions/upload-artifact@v4
  with:
    name: ios-app
    path: build/*.ipa
