name: iOS Build

on:
  push:
    branches: [ main ]       # mainブランチにpushされたら自動実行
  workflow_dispatch:         # 手動実行も可能

jobs:
  build:
    runs-on: macos-latest    # 最新macOSランナーで実行

    steps:
    # 1. リポジトリをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. Xcodeプロジェクトのスキーム確認
    - name: List Xcode schemes
      run: |
        xcodebuild -project MyiOSApp.xcodeproj -list

    # 3. Xcodeでアーカイブ（.xcarchive）を作成
    - name: Build iOS app
      run: |
        xcodebuild \
          -project MyiOSApp.xcodeproj \       # プロジェクト名
          -scheme FXForecastGame \            # スキーム名（クラウドで確認済み）
          -sdk iphoneos \
          -configuration Release \
          -archivePath $PWD/build/FXForecastGame.xcarchive archive

    # 4. .ipaにエクスポート
    - name: Export .ipa
      run: |
        xcodebuild -exportArchive \
          -archivePath $PWD/build/FXForecastGame.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath $PWD/build

    # 5. .ipaをArtifactとしてアップロード
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: build/*.ipa
