name: iOS Build (App Store)

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*' # タグを打ったときのみ実行

jobs:
  build:
    runs-on: macos-latest

    steps:
    # 1. リポジトリをチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        persist-credentials: true

    # 2. CocoaPods があればインストール
    - name: Install dependencies
      run: |
        if [ -f "MyiOSApp/Podfile" ]; then
          pod install --project-directory=MyiOSApp
        fi

    # 3. Provisioning Profile（App Store用）を復元
    - name: Decode and install App Store provisioning profile
      run: |
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        echo "$APPSTORE_MOBILEPROVISION" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/MyiOSApp_AppStore.mobileprovision
      env:
        APPSTORE_MOBILEPROVISION: ${{ secrets.APPSTORE_MOBILEPROVISION }}

    # 4. App Store 用証明書を Keychain にインポート
    - name: Import App Store certificate to keychain
      run: |
        echo "$CERTIFICATE_APPSTORE" | base64 --decode > /tmp/certificate_appstore.p12
        security create-keychain -p "$CERTIFICATE_APPSTORE_PASSWORD" build.keychain
        security import /tmp/certificate_appstore.p12 -k ~/Library/Keychains/build.keychain -P "$CERTIFICATE_APPSTORE_PASSWORD" -T /usr/bin/codesign
        security list-keychains -s ~/Library/Keychains/build.keychain
        security default-keychain -s ~/Library/Keychains/build.keychain
        security unlock-keychain -p "$CERTIFICATE_APPSTORE_PASSWORD" ~/Library/Keychains/build.keychain
        security set-key-partition-list -S apple-tool:,apple: -s -k "$CERTIFICATE_APPSTORE_PASSWORD" ~/Library/Keychains/build.keychain
        security find-identity -v -p codesigning || true
      env:
        CERTIFICATE_APPSTORE: ${{ secrets.CERTIFICATE_APPSTORE }}
        CERTIFICATE_APPSTORE_PASSWORD: ${{ secrets.CERTIFICATE_APPSTORE_PASSWORD }}

    # 5. DerivedData をクリーン
    - name: Clean DerivedData
      run: rm -rf ~/Library/Developer/Xcode/DerivedData

    # 6. アーカイブ作成（App Store用）
    - name: Build archive (App Store)
      working-directory: MyiOSApp
      run: |
        set -e
        xcodebuild clean -project MyiOSApp.xcodeproj -scheme MyiOSApp -configuration Release
        xcodebuild \
          -project MyiOSApp.xcodeproj \
          -scheme MyiOSApp \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $PWD/build/MyiOSApp_AppStore.xcarchive \
          archive \
          CODE_SIGN_STYLE=Manual \
          CODE_SIGN_IDENTITY="Apple Distribution: Tochishita Haruki (8UT7U3MV6X)" \
          PROVISIONING_PROFILE_SPECIFIER="MyiOSApp_AppStore_Profile" \
          DEVELOPMENT_TEAM="${{ secrets.TEAM_ID }}"

    # 7. .ipa エクスポート（App Store）
    - name: Export IPA (App Store)
      working-directory: MyiOSApp
      run: |
        set -e
        xcodebuild -exportArchive \
          -archivePath $PWD/build/MyiOSApp_AppStore.xcarchive \
          -exportOptionsPlist ExportOptions_AppStore.plist \
          -exportPath $PWD/build
        echo "Contents of build directory:"
        ls -al build || true

    # 8. アップロード（App Store Connect）
    - name: Upload IPA to App Store Connect
      run: |
        xcrun altool --upload-app \
          -f MyiOSApp/build/MyiOSApp.ipa \
          -t ios \
          -u "${{ secrets.APPLE_ID }}" \
          -p "${{ secrets.APPSTORE_APP_SPECIFIC_PASSWORD }}"
