name: iOS Build

# いつ実行するか
on:
  push:
    branches: [ main ]       # mainブランチにpushされたら自動実行
  workflow_dispatch:         # 手動実行も可能

jobs:
  build:
    runs-on: macos-latest    # 最新macOSランナーで実行

    steps:
    # 1. リポジトリをチェックアウト
    - name: Checkout code
      uses: actions/checkout@v3

    # 2. スキーム確認（クラウド上で有効なスキーム名を確認）
    - name: List Xcode schemes
      run: |
        xcodebuild -workspace MyiOSApp.xcworkspace -list

    # 3. CocoaPodsやSwift Package Managerなど依存関係があればインストール
    - name: Install dependencies
      run: |
        # CocoaPodsなら
        pod install || true
        # SPMなら不要

    # 4. Xcodeでアーカイブ（.xcarchive）を作成
    - name: Build iOS app
      run: |
        xcodebuild \
          -workspace MyiOSApp.xcworkspace \  # ワークスペース名
          -scheme FXForecastGame \            # スキーム名（クラウドで確認したもの）
          -sdk iphoneos \
          -configuration Release \
          -archivePath $PWD/build/FXForecastGame.xcarchive archive

    # 5. .ipaにエクスポート
    - name: Export .ipa
      run: |
        xcodebuild -exportArchive \
          -archivePath $PWD/build/FXForecastGame.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath $PWD/build

    # 6. .ipaをArtifactとしてアップロード
    - name: Upload IPA
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: build/*.ipa
