name: iOS Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    # 1. リポジトリをチェックアウト
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. CocoaPods があればインストール
    - name: Install dependencies
      run: |
        if [ -f "Podfile" ]; then
          pod install
        fi
      working-directory: MyiOSApp

    # 3. Xcodeでアーカイブ作成
    - name: Build app (archive)
      run: |
        xcodebuild \
          -project MyiOSApp.xcodeproj \
          -scheme MyiOSApp \
          -sdk iphoneos \
          -configuration Release \
          -archivePath $PWD/build/MyiOSApp.xcarchive \
          -allowProvisioningUpdates archive
      working-directory: MyiOSApp

    # 4. .ipaにエクスポート
    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath $PWD/build/MyiOSApp.xcarchive \
          -exportOptionsPlist ExportOptions.plist \
          -exportPath $PWD/build \
          -allowProvisioningUpdates
      working-directory: MyiOSApp

    # 5. .ipaをArtifactとしてアップロード
    - name: Upload IPA artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyiOSApp-ipa
        path: MyiOSApp/build/*.ipa